version: '3.8'

services:
    app:
        build:
            context: .
            args:
                UID: 1000
                GID: 1000
        container_name: lolo_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            TZ: Asia/Kolkata # Set timezone for app container
        networks:
            - lolo
        depends_on:
            db:
                condition: service_healthy

    web:
        image: nginx:alpine
        container_name: lolo_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            TZ: Asia/Kolkata # Set timezone for Nginx container
        # Command to install tzdata, set Asia/Kolkata, and run Nginx
        command: /bin/sh -c "apk add --no-cache tzdata && cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && exec nginx -g 'daemon off;'"
        depends_on:
            - app
        networks:
            - lolo

    db:
        image: mysql:8.0
        container_name: lolo_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: lolo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            TZ: Asia/Kolkata # Set timezone for MySQL container
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - lolo
        command: --default-time-zone='+05:30'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-proot" ]
            retries: 3
            timeout: 5s

volumes:
    dbdata:
        # Named volume for MySQL persistence

networks:
    lolo:
        driver: bridge # Default Docker bridge networking
