version: '3.8'

services:
    app:
        build:
            context: .
            args:
                UID: 1000
                GID: 1000
        container_name: lolo_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - lolo
        depends_on:
            db:
                condition: service_healthy

    web:
        image: nginx:alpine
        container_name: lolo_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - lolo

    db:
        image: mysql:8.0
        container_name: lolo_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: lolo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - lolo
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-proot" ]
            retries: 3
            timeout: 5s

volumes:
    dbdata:


networks:
    lolo:
        driver: bridge
